[alias]
build-static-ffi = "build --frozen --profile maxperf --package firewood-ffi --features ethhash,logger"
build-profile-ffi = "build --frozen --profile profiling --package firewood-ffi --features ethhash,logger"
