# because apparently caches are isolated across branches
name: default-branch-cache

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # @v4 -> v4.2.2
      - uses: dtolnay/rust-toolchain@631a55b12751854ce901bb631d5902ceb48146f7 # @stable
        with:
          components: clippy,rustfmt
      - uses: Swatinem/rust-cache@779680da715d629ac1d338a641029a2f4372abb5 # @v2 -> v2.8.2
        with:
          save-if: "false"
          shared-key: "debug-no-features"
      - name: Check
        run: cargo check --workspace --all-targets
      - name: Build
        run: cargo build --workspace --all-targets
