name: ffi-nix

on:
  push:
    branches: [main]
  pull_request:
    paths:
      - ffi/flake.nix
      - ffi/flake.lock
      - ffi/go.mod
      - ffi/go.sum

jobs:
  ffi-nix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: DeterminateSystems/nix-installer-action@786fff0690178f1234e4e1fe9b536e94f5433196 # v20
      - uses: DeterminateSystems/magic-nix-cache-action@565684385bcd71bad329742eefe8d12f2e765b39 #v13
      - name: Check that FFI flake is up-to-date
        run: ./scripts/run-just.sh check-ffi-flake
      - name: Test nix build of Golang FFI bindings
        run: ./scripts/run-just.sh test-ffi-nix

